micronaut:
  application:
    name: dictionary
  server:
    port: ${PORT:8080}
    cors:
      enabled: true
      configuration:
        web:
          allowedMethods:
            - POST
            - PUT
            - DELETE
            - GET
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
jpa:
  default:
    entity-scan:
      packages: 'org.incubyte'
netty:
  default:
    allocator:
      max-order: 3
